version: 1.0.{build}
image: Visual Studio 2017
before_build:
  - nuget restore
build:
  project: I18NPortable.sln
  verbosity: minimal
after_test:
  - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\I18NPortable.UnitTests\bin\Debug\I18NPortable.UnitTests.dll" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\I18NPortable_coverage.xml 
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "I18NPortable_coverage.xml"